config/routes.rb
App::Application.routes.draw do
  resources :company_memberships

  resources :companies do
    member do
      get :set_current_company
    end
  end

  resources :comments

  resources :posts

  devise_for :users

  root :to => 'companies#index'

  get "assets/index"

end

app/models/company_membership.rb
class CompanyMembership < ActiveRecord::Base
  attr_accessible :user_id, :company_id, :name
  belongs_to :user
  belongs_to :company
end

app/controllers/company_memberships_controller.rb
class CompanyMembershipsController < ApplicationController
  before_filter :authenticate_user!

  # GET /company_memberships
  # GET /company_memberships.json
  def index
    @company_memberships = CompanyMembership.where(company_id: current_company.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @company_memberships, :meta => {:current_user => current_user, :current_company => current_company} }
    end
  end

  # GET /company_memberships/1
  # GET /company_memberships/1.json
  def show
    @company_membership = CompanyMembership.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company_membership }
    end
  end

  # GET /company_memberships/new
  # GET /company_memberships/new.json
  def new
    @company_membership = CompanyMembership.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company_membership }
    end
  end

  # GET /company_memberships/1/edit
  def edit
    @company_membership = CompanyMembership.find(params[:id])
  end

  # POST /company_memberships
  # POST /company_memberships.json
  def create
    @company_membership = CompanyMembership.new(params[:company_membership])

    respond_to do |format|
      if @company_membership.save
        format.html { redirect_to @company_membership, notice: 'Company membership was successfully created.' }
        format.json { render json: @company_membership, status: :created, location: @company_membership }
      else
        format.html { render action: "new" }
        format.json { render json: @company_membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /company_memberships/1
  # PUT /company_memberships/1.json
  def update
    @company_membership = CompanyMembership.find(params[:id])

    respond_to do |format|
      if @company_membership.update_attributes(params[:company_membership])
        format.html { redirect_to @company_membership, notice: 'Company membership was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company_membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /company_memberships/1
  # DELETE /company_memberships/1.json
  def destroy
    @company_membership = CompanyMembership.find(params[:id])
    @company_membership.destroy

    respond_to do |format|
      format.html { redirect_to company_memberships_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/company_memberships_helper.rb
module CompanyMembershipsHelper
end

app/views/company_memberships/_form.html.erb
<%= form_for(@company_membership) do |f| %>
  <% if @company_membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company_membership.errors.count, "error") %> prohibited this company_membership from being saved:</h2>

      <ul>
      <% @company_membership.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/company_memberships/edit.html.erb
<h1>Editing company_membership</h1>

<%= render 'form' %>

<%= link_to 'Show', @company_membership %> |
<%= link_to 'Back', company_memberships_path %>

app/views/company_memberships/index.html.erb
<h1>Listing company_memberships</h1>

<table>
  <tr>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @company_memberships.each do |company_membership| %>
  <tr>
    <td><%= company_membership.user_id %></td>
    <td><%= link_to 'Show', company_membership %></td>
    <td><%= link_to 'Edit', edit_company_membership_path(company_membership) %></td>
    <td><%= link_to 'Destroy', company_membership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Company membership', new_company_membership_path %>

app/views/company_memberships/new.html.erb
<h1>New company_membership</h1>

<%= render 'form' %>

<%= link_to 'Back', company_memberships_path %>

app/views/company_memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @company_membership.user_id %>
</p>


<%= link_to 'Edit', edit_company_membership_path(@company_membership) %> |
<%= link_to 'Back', company_memberships_path %>